<?php if ($this->pageCount > 1 ){ ?>
<div class="paginator">
Страница <?php echo $this->current; ?> из <?php echo $this->last; ?>&nbsp;
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&laquo;</a>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
<?php if ($page != $this->current): ?> <a
	href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a> <?php else: ?>
<span><?php echo $page; ?></span> <?php endif; ?> <?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?><a href="<?php echo $this->url(array('page' => $this->next)); ?>">&raquo;</a><?php endif; ?>
</div>
<?php } ?>
