
<div class="header_left"></div>
<div class="header_right">
    <div class="navbar">
        <div class="navbar-inner">
            <?php
            echo $this->navigation()
                    ->menu()
                    ->setUlClass('pull-right nav')
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    ->render($this->mainNavigation);
            ?>
            <div class="clear"></div>
            <div class="pull-left username">Hi, <?php echo $this->loggedUser?$this->loggedUser->fullname:'Guest' ?>!</div>
        </div>
    </div>
</div>
<div class="clear"></div>