<form id="regform" name="regform" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" id="edit-project-form">
    <?php $elements = $this->form->getElements();
    foreach ($elements as $key => $element) : ?>
        <div class ="form-element">
            <label class="lineelement" for="<?php echo $key ?>"><?php echo $element->getLabel() ?></label>
            <?php echo $this->form->getElement($key); ?>
            <?php
            $messages = $element->getMessages();
            if (count($messages)):
                ?>
                <div class="errors">
                    <?php foreach ($messages as $message): ?>
                        <p><?php echo $message ?></p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    <?php endforeach; ?>
</form>


<div class="div_inquiryBtn"><!-- submit button -->
    <a href="#" onClick="window.document.forms['regform'].submit(); return false;" class="inquiryBtn_big">
        <span>
            <span>Register</span>
        </span>
    </a>
</div>