<form id="loginform" method="post" action="/admin/login">
	<div class="loginelement">
		<div class="grid_1">Имя</div>
		<input type="text" name="email" class="login-input"></input>
	</div>
	<div class="loginelement">
		<div class="grid_1">Пароль</div>
		<input type="password" name="password" class="login-input"></input>
	</div>
	<input type="submit" value="отправить" class="login-input"/>
</form>