<table class="table">
    <thead>
        <tr>
            <th>User</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->friends as $friend): ?>
            <tr>
                <td class="username"><?php echo $friend->Users->username ?></td>
                <td class="send-message span3">
                    <a class="send-message" user="<?php echo $friend->Users->id ?>" href="#">Send Message</a>
                    <?php if(in_array($friend->Users->id, $this->friendsList)): ?>
                    <a href="/friends/remove/id/<?php echo $friend->Users->id ?>">Remove from Friends</a>
                    <?php else: ?>
                    <a href="/friends/add/id/<?php echo $friend->Users->id ?>">Add to Friends</a>
                    <?php endif; ?>
                </td>
                <td class="clear"></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<section id="modals">
    <div id="dialog" class="modal hide fade in">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Message</h3>
        </div>
        <div class="modal-body">
            <form action="/messages/send" method="post">
                <div class="username"></div>
                <input type="hidden" name="recepient" value="0"/>
                <input type="hidden" name="sender" value="<?php echo $this->loggedUser->id ?>"/>
                <textarea style="height: 180px; width: 500px"  name="content"></textarea>
            </form>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn btn-primary">Send message</a>
        </div>
    </div>
</section>
