<?php echo $this->render('partials/form.phtml', 'default'); ?>
<a href="#" onClick="window.document.forms['submited-form'].submit(); return false;" class="inquiryBtn_big">
    <span>
        <span>Login</span>
    </span>
</a>
<br /><span>Forgot your password? <a href="<?php echo $this->url(array('controller' => 'forgot-password', 'action' => 'index'), 'default', true); ?>">Click here</a>.</span>