<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Error</title>
  <?php 
  echo $this->headLink();

echo $this->headScript();
echo $this->headMeta();
  ?>
</head>
<body>
	<div class="container_12 page topspace">
		<div class="grid_12">
			<div class="content">
				<?php
					echo $this->layout()->content;
				?>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</body>
</html>
