<?php

/**
 * Model_Firms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Firms extends Model_Base_Firms
{
    public function findByUserId($user_id) {
        $q = Doctrine_Query::create()
                ->from('Model_Firms as f')
                ->innerJoin('f.Favorites favorites on favorites.firm_id=f.id');

        $q->where('favorites.user_id = ?', $user_id);
        return $q->execute();
    }
}