<?php

/**
 * Model_Messages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Messages extends Model_Base_Messages
{

    public function getCountUnreadedMessages($user_id)
    {

        $q = Doctrine_Query::create()
                ->from('Model_Messages m')
                ->where('m.recepient_id = ?', $user_id)
                ->andWhere('m.is_readed = ?', 0)
        ;
        return $q->count();
    }

    public function getMessagesForUser($user_id)
    {

        $q = Doctrine_Query::create()
                ->from('Model_Messages m')
                ->innerJoin('Model_Users as recepient on recepient.id = m.recepient_id')
                ->where('m.recepient_id = ?', $user_id)
        ;
        return $q->execute();
    }

}