<?php

/**
 * Model_Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Users extends Model_Base_Users
{
    public function getRegistaredUser($current) {
        $q = Doctrine_Query::create()
                ->from('Model_Users user')
                ->where('id !=?', $current);
        return $q->execute();
        
    } 
}