Friends:
  connection: doctrine
  tableName: friends
  columns:
    user_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    friend_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
Messages:
  connection: doctrine
  tableName: messages
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    sender_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    recepient_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    message:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_readed:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
Users:
  connection: doctrine
  tableName: users
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    username:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fullname:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
