Friends:
  connection: doctrine
  tableName: friends
  columns:
    user_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    friend_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
  relations:
    Users:
      local: user_id
      foreign: id
      type: one
    Users_2:
      class: Users
      local: friend_id
      foreign: id
      type: one
Messages:
  connection: doctrine
  tableName: messages
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    sender_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    recepient_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    message:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_readed:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    time:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Users:
      local: sender_id
      foreign: id
      type: one
    Users_2:
      class: Users
      local: recepient_id
      foreign: id
      type: one
Users:
  connection: doctrine
  tableName: users
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    username:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fullname:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Friends:
      local: id
      foreign: user_id
      type: many
    Friends_2:
      class: Friends
      local: id
      foreign: friend_id
      type: many
    Messages:
      local: id
      foreign: sender_id
      type: many
    Messages_2:
      class: Messages
      local: id
      foreign: recepient_id
      type: many
